<a href="https://colab.research.google.com/github/shubheshswain91/Maths-for-Machine-Learning/blob/main/matrices_vectors_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**Adding and subtracting matrices**

In [3]:
matrix_a = np.array([[1,1,1],
                    [1,1,1],
                    [1,1,2]])

In [4]:
matrix_b = np.array([[1,3,1],
                     [1,3,1],
                     [1,3,8]])

In [5]:
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [6]:
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

**Applying operation to the elements**

In [7]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

Create vectorized function

In [8]:
# Creates a functions that adds 100

add_100 = lambda i: i + 100

#Create a vectorized function

vectorized_add_100 = np.vectorize(add_100)

In [9]:
# Apply function to elements

vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

**Calculate Dot Product Of Two Vectors**

In [10]:
#create two vectors

vector_a = np.array([1,2,3])

vector_b = np.array([4,5,6])



In [11]:
#method 1

np.dot(vector_a, vector_b)

32

In [12]:
#method 2

vector_a @ vector_b

32